-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 23:35:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema tickets
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`squad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`squad` (
  `squad_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`squad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `game_date` DATETIME NOT NULL,
  `home_squad_id` INT NOT NULL,
  `away_squad_id` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_Game_Squad_idx` (`home_squad_id` ASC) VISIBLE,
  INDEX `fk_Game_Squad1_idx` (`away_squad_id` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Squad`
    FOREIGN KEY (`home_squad_id`)
    REFERENCES `mydb`.`squad` (`squad_id`),
  CONSTRAINT `fk_Game_Squad1`
    FOREIGN KEY (`away_squad_id`)
    REFERENCES `mydb`.`squad` (`squad_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `seat` VARCHAR(20) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `game_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_Ticket_Game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_Ticket_Person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`game_id`),
  CONSTRAINT `fk_Ticket_Person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
